### ISSUE TITLE
Implement the New Landing Page

### ISSUE THREAD

**Issue by daiwik-swaminathan** [CS-Social-Good-CalPoly/Vera#274]
This task follows up on the work done in issue #208 where the design for the new home page was to be formulated. The design to implement can be found via this [Google Slides Link](https://docs.google.com/presentation/d/15MNWkiCLKsQ09sDw25AxHYh5u4ikmN4AsamH0Prik7c/edit?usp=sharing).

Feel free to make use of whatever libraries you'd like to ensure the closest possible resemblance to the design as specified.

**Comment by eliseemelia** [comment]
![Screenshot 2024-04-29 103848](https://github.com/CS-Social-Good-CalPoly/Vera/assets/62973237/a6a13c05-92e3-4f06-a980-9eff395c60be)
Google slides final layout converted to figma

**Comment by eliseemelia** [comment]
Developing on 274-Implement-the-New-Landing-Page branch.
Created 'LandingPage' page and changed the app.js homepage link to open landingpage instead of homepage.
Created 'LandingBanner' component to hold the main page image, a headline, and 2 buttons
Created 'LinkButton' component that opens a specific link when clicked
Finished 2/4 banners

**Comment by eliseemelia** [comment]
Created separate banner components:
- TextBanner is a title, body text, and a button group
- PhotoBanner is a photo and a text group (title, body text, button group)
